---
######################
# Video Stream Config
######################
visualize: True
video_stream: "ROSTopic"
### RosBag Input
#video_stream: "ROSBag"
bag_file: "/home/shivendra/Desktop/GuideCane/rosbags/mapping.bag"
topics:
    - "/d400/color/image_raw"
    - "/d400/depth/image_rect_raw"

publish_rate: 1

### Necessary for all input methods ###
rgb_input_topic: "/d400/color/image_raw"   # RGB Input topic to subscribe to
depth_input_topic: "/d400/depth/image_rect_raw"      #  Depth input topic to subscribe to
### Intel Realsense input
#video_stream: "RealSense"


### directory of images input
# video_stream: "RawImages"
#rgb_dir: "/home/epiphyte/Documents/Research/cane_ws/src/cane/segmentation/rgbd_output/RGB"
#depth_dir: "/home/epiphyte/Documents/Research/cane_ws/src/cane/segmentation/rgbd_output/depth"


############################
# Segmentation Model Config
############################
segmentation_model: "detectron"

model_weights: "/home/shivendra/Downloads/model_final_a54504.pkl"

model_config: "/home/shivendra/Desktop/computer_vision/instance-segmentation/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml"
